# Generated by Django 3.2.3 on 2021-05-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('H', 'High'), ('M', 'Medium'), ('L', 'Low')], max_length=128),
        ),
    ]
